import 'package:bin_yousuf_driver/core/constants/assets.dart';

class CategoryModel {
  CategoryModel({
    required this.image,
    required this.name,
    required this.subCategoryImage,
    required this.subCategory,
    required this.items,
  });
  String image;
  String name;
  String subCategoryImage;
  List<Map<String, dynamic>> subCategory;
  List<Map<String, dynamic>> items;
}

List<CategoryModel> categories = [
  CategoryModel(
    image: chawal,
    name: 'Chaawal',
    subCategoryImage: chawal2,
    subCategory: [],
    items: [
      {
        'pic': chawalPack,
        'name': 'Kainat Steam No 1',
        'price': '1,730',
        'weight': '20kg',
        'quantity': '',
      },
      {
        'pic': chawalPack,
        'name': '1121 Steam b2',
        'price': '1,730',
        'weight': '20kg',
        'quantity': '',
      },
      {
        'pic': chawalPack,
        'name': 'Kainat Steam No 1',
        'price': '1,730',
        'quantity': '',
        'weight': '5kg',
      },
      {
        'pic': chawalPack,
        'name': '1121 Steam b2',
        'price': '1,730',
        'quantity': '',
        'weight': '5kg',
      },
      {
        'pic': chawalPack,
        'name': 'Kainat Steam No 1',
        'price': '1,730',
        'quantity': '',
        'weight': '2.5kg',
      },
      {
        'pic': chawalPack,
        'name': '1121 Steam b2',
        'price': '1,730',
        'weight': '2.5kg',
        'quantity': '',
      },
    ],
  ),
  CategoryModel(
    image: daal,
    name: 'Daal',
    subCategoryImage: daal2,
    subCategory: [
      {
        'image': daalBag,
        'name': 'Daal',
        'weight': '20',
      },
      {
        'image': daalBag,
        'name': 'Daal',
        'weight': '5',
      },
      {
        'image': daalBag,
        'name': 'Daal',
        'weight': '2.5',
      }
    ],
    items: [
      {
        'pic': daalMong,
        'name': 'Daal Mong',
        'price': '1,730',
        'weight': '20kg',
        'quantity': '',
      },
      {
        'pic': daalSafaidChanna,
        'name': 'Safaid Channa',
        'price': '1,730',
        'weight': '20kg',
        'quantity': '',
      },
      {
        'pic': daalChannaSupreme,
        'name': 'Daal Channa Supreme',
        'price': '1,730',
        'weight': '20kg',
        'quantity': '',
      },
      {
        'pic': daalMasoor,
        'name': 'Masoor Daal',
        'price': '1,730',
        'weight': '20kg',
        'quantity': '',
      },
      {
        'pic': daalMong,
        'name': 'Daal Mong',
        'price': '1,730',
        'weight': '20kg',
        'quantity': '',
      },
      {
        'pic': daalSafaidChanna,
        'name': 'Safaid Channa',
        'price': '1,730',
        'weight': '20kg',
        'quantity': '',
      },
      {
        'pic': daalChannaSupreme,
        'name': 'Daal Channa Supreme',
        'price': '730',
        'weight': '5kg',
        'quantity': '',
      },
      {
        'pic': daalMasoor,
        'name': 'Masoor Daal',
        'price': '730',
        'weight': '5kg',
        'quantity': '',
      },
      {
        'pic': daalMong,
        'name': 'Daal Mong',
        'price': '730',
        'quantity': '',
        'weight': '5kg',
      },
      {
        'pic': daalSafaidChanna,
        'name': 'Safaid Channa',
        'price': '730',
        'weight': '5kg',
        'quantity': '',
      },
      {
        'pic': daalMasoor,
        'name': 'Masoor Daal',
        'price': '730',
        'weight': '2.5kg',
        'quantity': '',
      },
      {
        'pic': daalMong,
        'name': 'Daal Mong',
        'price': '730',
        'weight': '2.5kg',
        'quantity': '',
      },
      {
        'pic': daalSafaidChanna,
        'name': 'Safaid Channa',
        'price': '730',
        'weight': '2.5kg',
        'quantity': '',
      },
    ],
  ),
  CategoryModel(
      image: chakkiAata,
      name: 'Chakki Aata',
      subCategoryImage: chakkiAata2,
      subCategory: [],
      items: [
        {
          'pic': daalSafaidChanna,
          'name': 'Fine Chakki Aata',
          'price': '1,730',
          'weight': '20kg',
          'quantity': '',
        },
        {
          'pic': chakkiAata,
          'name': 'Mix Chakki Aata',
          'price': '1,730',
          'weight': '20kg',
          'quantity': '',
        },
        {
          'pic': chakkiAata,
          'name': 'Mix Chakki Aata',
          'price': '1,730',
          'weight': '20kg',
          'quantity': '',
        },
      ]),
  CategoryModel(
    image: besan,
    name: 'Besan',
    subCategoryImage: besan2,
    subCategory: [],
    items: [
      {
        'pic': chakkiBesan,
        'name': 'Besan Chakki',
        'price': '1,730',
        'weight': '20',
        'quantity': '',
      },
      {
        'pic': chakkiBesan,
        'name': 'Besan Chakki',
        'price': '1,730',
        'weight': '20',
        'quantity': '',
      },
      {
        'pic': chakkiBesan,
        'name': 'Besan Chakki',
        'price': '1,730',
        'weight': '20',
        'quantity': '',
      },
      {
        'pic': chakkiBesan,
        'name': 'Besan Chakki',
        'price': '1,730',
        'weight': '20',
        'quantity': '',
      },
    ],
  ),
  CategoryModel(
    image: shakkar,
    name: 'Shakkar/Gur',
    subCategoryImage: shakkar2,
    subCategory: [],
    items: [
      {
        'pic': shakkar3,
        'name': 'Shakkar Desi',
        'price': '1,730',
        'weight': '20',
        'quantity': '',
      },
      {
        'pic': shakkar3,
        'name': 'Shakkar No2',
        'price': '1,730',
        'weight': '20',
        'quantity': '',
      },
      {
        'pic': shakkar3,
        'name': 'Shakkar Desi',
        'price': '1,730',
        'weight': '20',
        'quantity': '',
      },
      {
        'pic': shakkar3,
        'name': 'Shakkar Desi',
        'price': '1,730',
        'weight': '20',
        'quantity': '',
      },
    ],
  ),
  CategoryModel(
    image: chai,
    name: 'Chaye',
    subCategoryImage: chai2,
    subCategory: [],
    items: [
      {
        'pic': chaiGreen,
        'name': 'Green Tea',
        'price': '1,730',
        'weight': '20',
        'quantity': '',
      },
      {
        'pic': chaiBlack,
        'name': 'Black Tea',
        'price': '1,730',
        'weight': '20',
        'quantity': '',
      },
      {
        'pic': chaiGreen,
        'name': 'Green Tea',
        'price': '1,730',
        'weight': '20',
        'quantity': '',
      },
      {
        'pic': chaiBlack,
        'name': 'Black Tea',
        'price': '1,730',
        'weight': '20',
        'quantity': '',
      },
    ],
  ),
  CategoryModel(
    image: masalay,
    name: 'Masalay',
    subCategoryImage: masalay2,
    subCategory: [
      {
        'image': masalay,
        'name': 'Masalay',
        'weight': '20',
      },
      {
        'image': masalay,
        'name': 'Masalay',
        'weight': '5',
      },
      {
        'image': masalay,
        'name': 'Masalay',
        'weight': '2.5',
      }
    ],
    items: [
      {
        'pic': daalBag,
        'name': 'Gol Mirch',
        'price': '1,730',
        'weight': '20kg',
        'quantity': '',
      },
      {
        'pic': daalBag,
        'name': 'Ajwain',
        'price': '1,730',
        'weight': '20kg',
        'quantity': '',
      },
      {
        'pic': daalBag,
        'name': 'Gol Mirch',
        'price': '1,730',
        'weight': '20kg',
        'quantity': '',
      },
      {
        'pic': daalSafaidChanna,
        'name': 'Malka Masoor',
        'price': '1,730',
        'weight': '20kg',
        'quantity': '',
      },
      {
        'pic': daalChannaSupreme,
        'name': 'Zeera Irani',
        'price': '730',
        'weight': '5kg',
        'quantity': '',
      },
      {
        'pic': daalMasoor,
        'name': 'Zeera Hindustani',
        'price': '730',
        'weight': '5kg',
        'quantity': '',
      },
      {
        'pic': daalMong,
        'name': 'Laal Mirch Powder',
        'price': '730',
        'weight': '5kg',
        'quantity': '',
      },
      {
        'pic': daalSafaidChanna,
        'name': 'Gol Mirch',
        'price': '730',
        'weight': '5kg',
        'quantity': '',
      },
      {
        'pic': daalMasoor,
        'name': 'Sabat Masoor',
        'price': '730',
        'weight': '2.5kg',
        'quantity': '',
      },
      {
        'pic': daalMong,
        'name': 'Laal Mirch Powder',
        'price': '730',
        'weight': '2.5kg',
        'quantity': '',
      },
      {
        'pic': daalSafaidChanna,
        'name': 'Zeera Irani',
        'price': '730',
        'weight': '2.5kg',
        'quantity': '',
      },
    ],
  ),
  CategoryModel(
    image: mustardOil,
    name: 'Sarsoun Ka Tail',
    subCategoryImage: mustardOil2,
    subCategory: [],
    items: [
      {
        'pic': mustardOil,
        'name': 'Sarsoun Ka Tail',
        'price': '730',
        'weight': '5kg',
        'quantity': '',
      },
      {
        'pic': mustardOil,
        'name': 'Sarsoun Ka Tail',
        'price': '730',
        'weight': '1kg',
        'quantity': '',
      },
      {
        'pic': mustardOil,
        'name': 'Sarsoun Ka Tail',
        'price': '730',
        'weight': '0.5kg',
        'quantity': '',
      },
      {
        'pic': mustardOil,
        'name': 'Sarsoun Ka Tail',
        'price': '730',
        'weight': '250g',
        'quantity': '',
      },
      {
        'pic': mustardOil,
        'name': 'Sarsoun Ka Tail',
        'price': '730',
        'weight': '125g',
        'quantity': '',
      },
    ],
  ),
  CategoryModel(
    image: bajra,
    name: 'Bajra',
    subCategoryImage: bajra2,
    subCategory: [],
    items: [
      {
        'pic': chaiGreen,
        'name': 'Bajra',
        'price': '1,730',
        'weight': '20',
        'quantity': '',
      },
      {
        'pic': chaiBlack,
        'name': 'Bajra',
        'price': '1,730',
        'weight': '20',
        'quantity': '',
      },
      {
        'pic': chaiGreen,
        'name': 'Bajra',
        'price': '1,730',
        'weight': '20',
        'quantity': '',
      },
      {
        'pic': chaiBlack,
        'name': 'Bajra',
        'price': '1,730',
        'weight': '20',
        'quantity': '',
      },
    ],
  ),
];
